sudo: true
language: bash
services:
  - docker
branches:
  only:
    - main
addons:
  ssh_known_hosts: $HOST_IP

before_install:
  - openssl aes-256-cbc -K $encrypted_8fa791b16dd7_key -iv $encrypted_8fa791b16dd7_iv
    -in id_rsa_deploy.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa

script:
  - docker build -t jasonzza/sneaker:latest -f Dockerfile .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push jasonzza/sneaker:latest
  - scp -o "StrictHostKeyChecking no" docker-compose.yml $USER@$HOST_IP:$PUBLISH_PATH
  - ssh -o "StrictHostKeyChecking no" $USER@$HOST_IP "cd $PUBLISH_PATH;docker-compose down;docker-compose pull;docker-compose up -d;exit"
